// Phase II: one record per museum accession or intact mural, never per photograph.
// Met photographs are copied locally only after the Open Access API confirms isPublicDomain.
const art = id => `${import.meta.env?.BASE_URL || './'}art/met-${id}.jpg`
const met = [
  ['44799','易县三彩罗汉坐像','Arhat (Luohan)','约1000年','ca. 1000','三彩釉炻器','Stoneware with three-color glaze','21.76','写实塑造的罗汉端坐沉思；这是大都会收藏的第二尊易县罗汉，与编号20.114为两件不同作品。','A life-size contemplative arhat: the Met’s second Yixian figure, distinct from accession 20.114.','sculpture'],
  ['42733','弥勒佛立像','Buddha Maitreya','北魏，486年','Northern Wei, dated 486','鎏金青铜','Gilt bronze','26.123','纪年造像让北魏佛教雕塑的形式变化有了可核对的时间坐标。','This dated image provides a firm chronological point for Northern Wei Buddhist sculpture.','bronze'],
  ['42163','阿弥陀佛坐像','Buddha, probably Amitabha','唐代，7世纪初','Tang dynasty, early 7th century','夹纻漆塑','Dry lacquer','19.186','轻质夹纻漆塑保留了早期唐代大型佛像的安详体量。','A rare surviving dry-lacquer image preserves the calm monumentality of early Tang Buddhist sculpture.','sculpture'],
  ['39666','龙纹青花罐','Jar with dragon','明代，15世纪初','Ming dynasty, early 15th century','景德镇青花瓷','Blue-and-white porcelain','37.191.1','游龙与缠枝纹在白瓷上展开，呈现明初景德镇御用瓷的气势。','A dragon and scrolling ornament spread across this early Ming blue-and-white jar.','ceramic'],
  ['39637','蟠龙纹玉环','Ring with knotted dragon','公元前3世纪','3rd century BCE','软玉','Nephrite','1985.214.99','盘绕的龙身被收束进圆形玉环，展示早期玉雕的抽象力量。','The coiled dragon is compressed into a circular jade form of striking economy.','jade'],
  ['42183','叶形银盘','Dish in the shape of a leaf','7世纪末至8世纪初','Late 7th–early 8th century','局部鎏金银','Partly gilt silver','1974.268.11','叶形盘把自然形态化为精巧的唐代金银器。','This leaf-shaped dish turns a natural form into finely worked Tang silver.','metal'],
  ['843765','鹅形熏炉','Incense burner in the shape of a goose','明代，15世纪初','Ming dynasty, early 15th century','铜合金','Copper alloy','2020.335a, b','鹅形炉将焚香器具与生动的动物造型合为一体。','A goose-shaped burner joins an incense vessel with lively animal modelling.','bronze'],
  ['42229','豇豆红釉瓶','Vase with peach-bloom glaze','清代，1713—1722年','Qing dynasty, 1713–1722','釉瓷','Glazed porcelain','14.40.377','釉色在粉红与深红之间变化，显示清代瓷工对窑变的精细掌控。','The shifting pink-red glaze records Qing potters’ control of kiln effects.','ceramic'],
  ['856282','山水纹掐丝珐琅插屏','Table screen with landscape','15世纪后半叶','Second half of the 15th century','掐丝珐琅','Cloisonné enamel','2022.10a, b','小型插屏把山水图景嵌入金属胎与珐琅色彩之中。','A compact landscape is rendered in metal cloisons and coloured enamel.','bronze'],
  ['49156','康熙南巡图卷第三卷：济南至泰山','The Kangxi Emperor’s Southern Inspection Tour, Scroll Three: Ji’nan to Mount Tai','约1698年','Datable to 1698','绢本水墨设色手卷','Handscroll; ink and colour on silk','1979.5a–d','长卷以连续场景展开康熙帝南巡自济南至泰山的城市与山川。','The handscroll unfolds towns and terrain from Ji’nan to Mount Tai on the Kangxi emperor’s southern tour.','painting'],
  ['42162','弥勒佛三尊像','Buddha Maitreya Altarpiece','北魏，524年','Northern Wei, dated 524','鎏金青铜','Gilt bronze','38.158.1a–n','有纪年的弥勒佛龛将主尊与随侍造像组织成完整的礼拜空间。','A dated Maitreya ensemble arranges its figures into a portable devotional setting.','bronze'],
  ['39901','《照夜白图》','Night-Shining White','唐代，约750年','Tang dynasty, ca. 750','纸本水墨','Ink on paper','1977.78','韩幹笔下的骏马被系于木桩，挣动的形态成为中国古代绘画名作。','Attributed to Han Gan, the tethered horse strains with an energy rare in surviving Tang painting.','painting'],
  ['775525','坐姿童俑','Sitting boy','12世纪','12th century','陶胎施化妆土','Earthenware with slip','2024.276','孩童的坐姿与神情保留了宋代陶塑对日常人物的细致观察。','The child’s posture and expression show close observation of everyday life in ceramic sculpture.','ceramic'],
  ['40055','《明皇幸蜀图》','Emperor Xuanzong’s Flight to Shu','12世纪中叶','Mid-12th century','绢本水墨设色描金','Ink, colour and gold on silk','41.138','山路中的帝王队伍，借唐代历史叙事呈现后世画家的山水想象。','An imperial party winds through mountains in a later painter’s imagining of Tang history.','painting'],
  ['48948','《十六罗汉图》','The Sixteen Luohans','1591年','Dated 1591','纸本水墨设色手卷','Handscroll; ink and colour on paper','1986.266.4','十六罗汉题材在晚明画卷中延续，群像各具姿态。','This late Ming rendering continues the Sixteen Luohans tradition with individually posed figures.','painting'],
  ['36131','《山水诗画册》十五开','Landscapes with poems: fifteen leaves','1688年','Dated 1688','册页十五开','Fifteen leaves from an album','1981.4.1a–o','这十五开属一套原有十八开的画册，画与诗并置，可逐开阅读。','Fifteen leaves from an eighteen-leaf album pair landscape with verse.','painting'],
  ['39936','《竹雀图》','Finches and bamboo','12世纪初','Early 12th century','绢本水墨设色手卷','Handscroll; ink and colour on silk','1981.278','雀鸟与竹枝在留白间相互呼应，体现宋代花鸟画的凝练观察。','Finches and bamboo meet across open silk in a finely observed Song bird-and-flower painting.','painting'],
  ['40081','《王羲之观鹅图》','Wang Xizhi Watching Geese','约1295年','ca. 1295','纸本水墨设色','Ink and colour on paper','1973.120.6','王羲之爱鹅的故事成为元代画家表达隐逸情怀的题材。','The calligrapher Wang Xizhi’s love of geese becomes a Yuan image of cultivated retreat.','painting'],
  ['39668','《古木遥岑图》','Old Trees, Level Distance','约1080年','ca. 1080','绢本水墨设色手卷','Handscroll; ink and colour on silk','1981.276','古木与远山在平远构图中层层退去，传达北宋山水的辽阔。','Ancient trees and distant hills recede through the level-distance composition.','painting'],
  ['45636','《虞山林壑图》','Woods and Valleys of Mount Yu','1372年','Dated 1372','纸本水墨','Ink on paper','1973.120.8','虞山的林木、溪谷与皴笔构成一处可以神游的山水。','Trees, valleys, and textured brushwork evoke a landscape of Mount Yu.','painting'],
  ['60870','云龙纹漆经箱','Sutra box with dragons amid clouds','明永乐，1403—1424年','Ming Yongle reign, 1403–1424','红漆戗金、黄铜锁','Incised red lacquer with gold inlay and brass lock','2001.584a–c','云龙纹围绕经箱展开，反映明初漆器与佛教经典容器的结合。','Cloud-and-dragon ornament surrounds this early Ming container for Buddhist sutras.','lacquer'],
  ['40215','庭园人物纹雕漆盘','Tray with women and boys on a garden terrace','14世纪','14th century','雕红漆','Carved red lacquer','2015.500.1.31','层叠雕漆在盘面刻出庭园中的人物活动。','Layers of carved red lacquer create a garden scene populated by women and children.','lacquer'],
  ['39918','《廉颇蔺相如列传》书法卷','Biographies of Lian Po and Lin Xiangru','约1095年','ca. 1095','纸本水墨手卷','Ink on paper handscroll','1989.363.4','书写史记名篇的长卷，以行草笔势使历史人物故事重新展开。','This calligraphic handscroll renders a celebrated historical narrative in lively brushwork.','painting'],
  ['42731','辽代水月观音木像','Water-Moon Guanyin','辽代，11世纪','Liao dynasty, 11th century','柳木雕像','Willow wood','28.56','观音自在坐于岩座；它与馆内另一尊1385年纪年的水月观音相隔数世纪。','Guanyin sits at ease on a rocky base, centuries before the Met’s other dated Water-Moon image.','sculpture'],
]

export const expandedRelics = met.map(([id,nameZh,nameEn,dateZh,dateEn,mediumZh,mediumEn,accession,descZh,descEn,category]) => ({
  id:`met-${id}`, museumId:'met', category, image:art(id), nameZh,nameEn,dateZh,dateEn,mediumZh,mediumEn,accession,descZh,descEn,
  originZh:id==='44799'?'传出河北易县西部山洞':'中国，具体作地或出土地未详',
  originEn:id==='44799'?'Reportedly from caves west of Yixian, Hebei':'China; precise production site or findspot unknown',
  originPrecision:id==='44799'?'inferred':'unknown',homePoint:null,
  source:`https://www.metmuseum.org/art/collection/search/${id}`,
  imageSource:`https://collectionapi.metmuseum.org/public/collection/v1/objects/${id}`,
  creditZh:'图：大都会艺术博物馆，Open Access 公有领域；藏品信息：馆方目录。',
  creditEn:'Image: The Metropolitan Museum of Art, Open Access/public domain; object data: museum catalogue.',
})).concat([
  {id:'yixian-penn',museumId:'penn',category:'sculpture',image:`${import.meta.env?.BASE_URL || './'}art/yixian-penn-open.jpg`,nameZh:'易县三彩罗汉坐像',nameEn:'Luohan (Arhat)',dateZh:'辽至金代，约10—12世纪',dateEn:'Liao–Jin period, ca. 10th–12th century',mediumZh:'三彩釉陶',mediumEn:'Three-colour glazed earthenware',originZh:'传出河北易县',originEn:'Reportedly from Yixian, Hebei',originPrecision:'inferred',homePoint:null,descZh:'宾大博物馆收藏的易县罗汉群成员，1914年购自巴黎古董商Worch；确切原址仍应按“传出”理解。',descEn:'A Yixian-group luohan acquired from the Paris dealer Worch in 1914; its original site is reported rather than archaeologically secure.',accession:'C66A',source:'https://www.penn.museum/collections/object/151869',sourceExtra:'https://www.penn.museum/sites/expedition/the-luohan-that-came-from-afar/',imageSource:'https://commons.wikimedia.org/wiki/File:宾夕法尼亚大学考古学与人类学博物馆易县辽代三彩罗汉.jpg',creditZh:'图：Patrick20242023 / Wikimedia Commons，CC BY-SA 4.0；藏品信息：宾大博物馆。',creditEn:'Image: Patrick20242023 / Wikimedia Commons, CC BY-SA 4.0; object data: Penn Museum.'},
  {id:'yixian-nelson',museumId:'nelson',category:'sculpture',image:`${import.meta.env?.BASE_URL || './'}art/yixian-nelson-open.jpg`,nameZh:'易县三彩罗汉坐像',nameEn:'Luohan',dateZh:'辽至金代，907—1234年',dateEn:'Liao–Jin period, 907–1234',mediumZh:'三彩釉陶，高约118厘米',mediumEn:'Three-colour glazed earthenware, approx. 118 cm high',originZh:'传出河北易县',originEn:'Reportedly from Yixian, Hebei',originPrecision:'inferred',homePoint:null,descZh:'罗汉双手平放于膝，作禅定姿；馆方记录1934年购自卢芹斋，易县地点见馆方主题标签。',descEn:'A meditating luohan with hands resting on the lap, bought from C. T. Loo in 1934; Yixian appears in the museum’s subject indexing.',accession:'34-6',source:'https://art.nelson-atkins.org/objects/15683/luohan',imageSource:'https://commons.wikimedia.org/wiki/File:Nelson-Atkins_Luohan_34-6.jpg',creditZh:'图：ArtHistVista / Wikimedia Commons，CC BY-SA 4.0；藏品信息：纳尔逊—阿特金斯艺术博物馆。',creditEn:'Image: ArtHistVista / Wikimedia Commons, CC BY-SA 4.0; object data: Nelson-Atkins Museum of Art.'},
  {id:'guangsheng-nelson',museumId:'nelson',category:'painting',image:`${import.meta.env?.BASE_URL || './'}art/guangsheng-nelson-open.jpg`,nameZh:'广胜下寺《炽盛光佛会图》',nameEn:'The Assembly of Tejaprabha',dateZh:'元代，14世纪初',dateEn:'Yuan dynasty, early 14th century',mediumZh:'寺观壁画',mediumEn:'Temple wall painting',originZh:'山西洪洞广胜下寺主殿西壁',originEn:'West wall of the main hall, Guangsheng Lower Monastery, Hongdong, Shanxi',originLat:36.27,originLng:111.68,originPrecision:'site',homePoint:[36.27,111.68],descZh:'炽盛光佛与众神像曾绘于广胜下寺主殿西壁；现与纽约、费城的相关壁画分藏不同机构。',descEn:'Tejaprabha and attendant deities once occupied the lower monastery’s west wall; related murals now reside in several museums.',accession:'32-91/1',source:'https://art.nelson-atkins.org/objects/14590/the-assembly-of-tejaprabha',imageSource:'https://commons.wikimedia.org/wiki/File:The_Assembly_of_Tejaprabha_-_Google_Art_Project.jpg',creditZh:'图：Google Art Project / Wikimedia Commons，PD-Art；馆藏信息：纳尔逊—阿特金斯艺术博物馆。',creditEn:'Image: Google Art Project / Wikimedia Commons, PD-Art; object data: Nelson-Atkins Museum of Art.'},
  {id:'guangsheng-penn-medicine',museumId:'penn',category:'painting',image:`${import.meta.env?.BASE_URL || './'}art/guangsheng-penn-medicine-open.jpg`,nameZh:'广胜下寺《药师佛图》壁画',nameEn:'Medicine Buddha mural',dateZh:'明代，约1476年',dateEn:'Ming dynasty, ca. 1476',mediumZh:'寺观壁画，约5.33 × 8.8米',mediumEn:'Temple wall painting, approx. 5.33 × 8.8 m',originZh:'山西洪洞广胜下寺',originEn:'Guangsheng Lower Monastery, Hongdong, Shanxi',originLat:36.27,originLng:111.68,originPrecision:'site',homePoint:[36.27,111.68],descZh:'宾大收藏的明代药师佛巨幅壁画，馆方记录1927年购自卢芹斋；它与另一幅炽盛光佛壁画为两面不同的墙。',descEn:'Penn’s large Ming Medicine Buddha wall painting was purchased from C. T. Loo in 1927; it is distinct from the museum’s companion Tejaprabha wall.',accession:'C688',source:'https://www.penn.museum/collections/object/307659',sourceExtra:'https://www.penn.museum/blog/preserving-buddhist-murals/',imageSource:'https://commons.wikimedia.org/wiki/File:Bhaisajyaguru_and_Assembly_tempera_painting_on_mud_mixed_with_seeds,_straw,_and_leaves_Ming_Dynasty,_1368-1644_CE_Shanxi_Province_China.jpg',creditZh:'图：Mary Harrsch / Wikimedia Commons，CC BY-SA 4.0；藏品信息：宾大博物馆。',creditEn:'Image: Mary Harrsch / Wikimedia Commons, CC BY-SA 4.0; object data: Penn Museum.'},
  {id:'guangsheng-penn-tejaprabha',museumId:'penn',category:'painting',image:`${import.meta.env?.BASE_URL || './'}art/guangsheng-penn-tejaprabha-open.jpg`,nameZh:'广胜下寺《炽盛光佛图》壁画',nameEn:'Tejaprabha mural',dateZh:'明代，约1476年',dateEn:'Ming dynasty, ca. 1476',mediumZh:'寺观壁画，多块壁画拼合',mediumEn:'Temple wall painting, reassembled from sections',originZh:'山西洪洞广胜下寺',originEn:'Guangsheng Lower Monastery, Hongdong, Shanxi',originLat:36.27,originLng:111.68,originPrecision:'site',homePoint:[36.27,111.68],descZh:'宾大收藏的另一面广胜下寺明代壁画；虽经多块分段重组，本展按一幅壁画而非多件计数。',descEn:'Penn’s second Ming wall painting from Guangsheng; its reconstructed sections are counted here as one mural, not separate objects.',accession:'C492',source:'https://collections.penn.museum/collections/object/16521',sourceExtra:'https://www.penn.museum/blog/preserving-buddhist-murals/',imageSource:'https://commons.wikimedia.org/wiki/File:Tejaprabha_and_Assembly_Tempera_on_mud_mixed_with_seeds,_straw_and_leaves,_1475_CE_Ming_Dynasty_Shanxi_Province,_Zhaocheng_Guangsheng_Monastery_China_02.jpg',imageCaptionZh:'图为壁画局部，并非整面墙。',imageCaptionEn:'The photograph shows a detail, not the entire wall.',creditZh:'图：Mary Harrsch / Wikimedia Commons，CC BY-SA 4.0；藏品信息：宾大博物馆。',creditEn:'Image: Mary Harrsch / Wikimedia Commons, CC BY-SA 4.0; object data: Penn Museum.'},
  {id:'guanyin-cleveland',museumId:'cma',category:'bronze',image:`${import.meta.env?.BASE_URL || './'}art/guanyin-cleveland-open.jpg`,nameZh:'水月观音鎏金铜像',nameEn:'Water and Moon (Potala) Guanyin',dateZh:'约900—1100年',dateEn:'c. 900–1100',mediumZh:'鎏金青铜，高17.6厘米',mediumEn:'Gilt bronze, 17.6 cm high',originZh:'中国，具体作地未详',originEn:'China; precise production site unknown',originPrecision:'unknown',homePoint:null,descZh:'小型鎏金铜观音采用水月观音的自在坐姿，与大型木雕、漆塑呈现同一题材的不同媒介。',descEn:'This small gilt-bronze Guanyin takes the Water-Moon pose, contrasting with larger wooden versions of the same subject.',accession:'1984.7',source:'https://www.clevelandart.org/art/1984.7',imageSource:'https://commons.wikimedia.org/wiki/File:Clevelandart_1984.7.jpg',creditZh:'图：克利夫兰艺术博物馆 / Wikimedia Commons，CC0 1.0；藏品信息：馆方目录。',creditEn:'Image: Cleveland Museum of Art / Wikimedia Commons, CC0 1.0; object data: museum catalogue.'},
])

export const collections = [
  {id:'yixian',nameZh:'易县罗汉',nameEn:'Yixian Luohans',descZh:'跨馆追寻传出河北易县的一组三彩罗汉；原址和断代仍有研究分歧，波士顿一尊的易县归属为专题研究判断。',descEn:'Follow the glazed luohans reportedly from Yixian across museums; provenance and dating remain debated, and the Boston attribution comes from research rather than its catalogue.',ids:['yixian-bm','yixian-met','met-44799','yixian-penn','yixian-nelson','yixian-rom','yixian-mfa']},
  {id:'guangsheng',nameZh:'广胜寺壁画',nameEn:'Guangsheng murals',descZh:'山西广胜下寺的壁画如今分藏纽约、堪萨斯城与费城；元、明壁画分开标记。',descEn:'Wall paintings from Guangsheng Lower Monastery are held in New York, Kansas City and Philadelphia; Yuan and Ming works are distinguished.',ids:['medicine-buddha','guangsheng-nelson','guangsheng-penn-medicine','guangsheng-penn-tejaprabha']},
  {id:'water-moon',nameZh:'水月观音',nameEn:'Water-Moon Guanyin',descZh:'同一自在坐形象，在不同时代与媒材中展现慈悲的姿态。',descEn:'The same relaxed pose of compassion appears in different periods and materials.',ids:['nelson-guanyin','water-moon-met','met-42731','guanyin-cleveland']},
]
