// Phase III: each record is an individually identified accession. Museum source
// and reusable photograph are tracked separately; no photo is a deliberate placeholder.
const photo = name => `${import.meta.env?.BASE_URL || './'}art/${name}`

export const supplementalRelics = [
  {
    id:'yixian-rom',museumId:'rom',category:'sculpture',image:photo('yixian-rom-open.jpg'),
    nameZh:'易县三彩罗汉坐像',nameEn:'Figure of a Luohan',dateZh:'辽至金代，11世纪',dateEn:'Liao–Jin period, 11th century',
    mediumZh:'模制施釉陶，高126.5厘米',mediumEn:'Moulded glazed earthenware, 126.5 cm high',
    originZh:'据传出自河北易县附近山洞',originEn:'Reportedly from a cave near Yixian, Hebei',originPrecision:'inferred',homePoint:null,
    descZh:'皇家安大略博物馆藏易县罗汉群的一尊。馆方提供的物件记录以“据传”限定易县地点；此处不把它当作经考古确认的出土地。',
    descEn:'One of the Yixian-group luohans at the Royal Ontario Museum. The ROM-supplied record qualifies the findspot as “reportedly” near Yixian, not archaeologically confirmed.',
    accession:'914.4.1',source:'https://artsandculture.google.com/asset/figure-of-a-luohan-unknown/-QFeB0dblF_4bQ',
    sourceExtra:'https://www.rom.on.ca/whats-on/galleries/matthews-family-court-chinese-sculpture',
    imageSource:'https://commons.wikimedia.org/wiki/File:Luohan_(arhat),_Yixian_cave,_Hebei_Province,_China,_Liao_Dynasty,_11th_century_-_Royal_Ontario_Museum_-_DSC09807.JPG',
    creditZh:'图：Daderot / Wikimedia Commons，CC0 1.0；藏品信息：皇家安大略博物馆提供的记录。',
    creditEn:'Image: Daderot / Wikimedia Commons, CC0 1.0; object data: ROM-supplied record.',
  },
  {
    id:'yixian-mfa',museumId:'mfa',category:'sculpture',image:null,
    nameZh:'三彩罗汉像（研究归入易县罗汉群）',nameEn:'Luohan (attributed to the Yixian group)',
    dateZh:'金代，12世纪（波士顿馆方断代）',dateEn:'Jin dynasty, 12th century (MFA dating)',
    mediumZh:'三彩釉炻器，高120.7厘米',mediumEn:'Stoneware with three-colour glaze, 120.7 cm high',
    originZh:'研究归入河北易县罗汉群；馆方条目未明示出土地',originEn:'Attributed to the Yixian group, Hebei; the MFA object entry does not specify a findspot',originPrecision:'inferred',homePoint:null,
    descZh:'波士顿馆方确认编号15.255、材质和金代断代；宾大馆藏研究及芝加哥大学专题将它列入易县罗汉群。出土地与时代归属不宜写成毫无争议的事实，且该件目前不在展出。',
    descEn:'The MFA confirms accession 15.255, medium and Jin dating; Penn Museum research and a University of Chicago project group it with the Yixian luohans. This attribution is not an excavated provenance; the object is not currently on view.',
    accession:'15.255',source:'https://collections.mfa.org/objects/13970',
    sourceExtra:'https://caeacollections.lib.uchicago.edu/view/15903/arhat-luohan?limit=100&offset=0&q=facet%2Cmetadata.WORK_Location5Name.en.keyword%2Cequals%2CMuseum+of+Fine+Arts%2C+Boston&q=filter%2Cparents%2Cequals%2C14454&sort=title.keyword',
    creditZh:'图片许可尚待确认，暂不复制馆方或三维模型图片；资料：波士顿美术博物馆、宾大博物馆与芝加哥大学专题。',
    creditEn:'Image reuse permission is unconfirmed; no museum or 3D-model image copied. Data: MFA Boston, Penn Museum and University of Chicago.',
  },
  {
    id:'bm-medicine-paradise',museumId:'bm',category:'painting',image:photo('bm-medicine-paradise-open.jpg'),
    nameZh:'敦煌《药师佛净土变》',nameEn:'Paradise of Bhaiṣajyaguru',dateZh:'唐代，9世纪',dateEn:'Tang dynasty, 9th century',
    mediumZh:'绢本水墨设色，206 × 167厘米',mediumEn:'Ink and colour on silk, 206 × 167 cm',
    originZh:'敦煌莫高窟第17窟（发现地）',originEn:'Cave 17, Mogao Caves, Dunhuang (findspot)',originPrecision:'site',homePoint:[40.0373,94.8041],
    descZh:'以药师佛为中心的净土图，描绘供养者、舞乐和经变故事；大英博物馆记录其发现于莫高窟藏经洞。这里的坐标是洞窟群概略位置。',
    descEn:'A painted paradise centred on the Medicine Buddha, with offerings, music and sutra narratives. The British Museum records Cave 17 as its findspot; the map point is approximate.',
    accession:'1919,0101,0.36',source:'https://www.britishmuseum.org/collection/object/A_1919-0101-0-36',
    imageSource:'https://commons.wikimedia.org/wiki/File:Anonymous-Paradise_of_Bhaishajyaguru.jpg',
    creditZh:'图：Wikimedia Commons，PD-Art / 公有领域标记；藏品信息：大英博物馆。',creditEn:'Image: Wikimedia Commons, PD-Art/public-domain mark; object data: British Museum.',
  },
  {
    id:'bm-five-planets',museumId:'bm',category:'painting',image:photo('bm-five-planets-open.jpg'),
    nameZh:'敦煌《炽盛光佛与五星图》',nameEn:'Tejaprabha Buddha and the Five Planets',dateZh:'唐代，897年',dateEn:'Tang dynasty, dated 897',
    mediumZh:'绢本水墨设色，80.4 × 55.4厘米',mediumEn:'Ink and colour on silk, 80.4 × 55.4 cm',
    originZh:'敦煌莫高窟第17窟（发现地）',originEn:'Cave 17, Mogao Caves, Dunhuang (findspot)',originPrecision:'site',homePoint:[40.0373,94.8041],
    descZh:'画上供养题记将作品系于897年，炽盛光佛乘车而行，五星被拟人化。大英博物馆确认发现于莫高窟藏经洞。',
    descEn:'A donor inscription dates the painting to 897. Tejaprabha rides a chariot among personified planets; the British Museum records Cave 17 as its findspot.',
    accession:'1919,0101,0.31',source:'https://www.britishmuseum.org/collection/object/A_1919-0101-0-31',
    imageSource:'https://commons.wikimedia.org/wiki/File:Tejaprabh%C4%81_Buddha_and_the_Five_Planets_by_Chang_Huai-hsing.jpg',
    creditZh:'图：Wikimedia Commons，PD-Art / 公有领域标记；藏品信息：大英博物馆。',creditEn:'Image: Wikimedia Commons, PD-Art/public-domain mark; object data: British Museum.',
  },
  {
    id:'vam-throne',museumId:'vam',category:'lacquer',image:photo('vam-throne-sourabh-open.jpg'),
    nameZh:'乾隆朝雕漆御座',nameEn:'Qianlong-period carved lacquer throne',dateZh:'清乾隆朝，约1775—1780年',dateEn:'Qing dynasty, Qianlong reign, c. 1775–1780',
    mediumZh:'木胎雕彩漆',mediumEn:'Carved polychrome lacquer on wood',
    originZh:'中国宫廷，南苑团河行宫归属为研究推测',originEn:'Chinese court; association with Tuanhe Travelling Palace is a scholarly hypothesis',originPrecision:'inferred',homePoint:null,
    descZh:'御座以龙纹等吉祥图案饰面。V&A确认馆藏号和乾隆朝断代；南苑团河行宫及1900年前后流散经历见馆方相关研究，原使用地点仍存不确定性。',
    descEn:'Dragons and auspicious motifs cover the imperial throne. The V&A confirms its accession and Qianlong date; the Tuanhe palace association and its dispersal around 1900 are discussed in collection research, but the original placement is not certain.',
    accession:'W.399:1, 2-1922',source:'https://www.vam.ac.uk/articles/va-trail-explore-as-a-family',
    imageSource:'https://commons.wikimedia.org/wiki/File:PXL_20231218_155438181.MP_Victoria_and_Albert_Museum_Artefacts_09_extremely_rare_Chinese_imperial_%22Nine_Dragon%22_lacquer_throne_d_(1736-1795)_of_the_Qing_dynasty.jpg',
    creditZh:'图：Sourabh.biswas003 / Wikimedia Commons，CC BY-SA 4.0；藏品信息：V&A。',
    creditEn:'Image: Sourabh.biswas003 / Wikimedia Commons, CC BY-SA 4.0; object data: V&A.',
  },
  {
    id:'vam-yixing-teapot',museumId:'vam',category:'ceramic',image:null,
    nameZh:'明末宜兴紫砂茶壶',nameEn:'Yixing teapot',dateZh:'明末，1625—1655年',dateEn:'Late Ming dynasty, 1625–1655',
    mediumZh:'宜兴紫砂陶',mediumEn:'Yixing zisha stoneware',
    originZh:'江苏宜兴（馆方标注的制作地）',originEn:'Yixing, Jiangsu (V&A production place)',originPrecision:'region',homePoint:[31.36,119.82],
    descZh:'V&A以馆藏号C.871&A-1936展示这件早期宜兴茶壶。暂未找到能与该编号精确对应、且允许再分发的照片，因此保留图像占位。',
    descEn:'The V&A identifies this early Yixing teapot as accession C.871&A-1936. No photograph both matched to this accession and cleared for redistribution was found, so the image is omitted.',
    accession:'C.871&A-1936',source:'https://www.vam.ac.uk/articles/teapots-through-time',
    creditZh:'图片许可或对应关系尚未确认，暂不复制馆方照片；藏品信息：V&A。',
    creditEn:'Image licence or exact match unconfirmed; no museum photograph copied. Object data: V&A.',
  },
]
