const asset = (name) => `${import.meta.env?.BASE_URL || './'}art/${name}`

export const museums = [
  { id: 'bm', nameZh: '大英博物馆', nameEn: 'The British Museum', cityZh: '伦敦', cityEn: 'London', countryZh: '英国', countryEn: 'United Kingdom', lat: 51.5194, lng: -0.1269 },
  { id: 'vam', nameZh: '维多利亚和阿尔伯特博物馆', nameEn: 'Victoria and Albert Museum', cityZh: '伦敦', cityEn: 'London', countryZh: '英国', countryEn: 'United Kingdom', lat: 51.4966, lng: -0.1722 },
  { id: 'met', nameZh: '大都会艺术博物馆', nameEn: 'The Metropolitan Museum of Art', cityZh: '纽约', cityEn: 'New York', countryZh: '美国', countryEn: 'United States', lat: 40.7794, lng: -73.9632 },
  { id: 'nelson', nameZh: '纳尔逊—阿特金斯艺术博物馆', nameEn: 'The Nelson-Atkins Museum of Art', cityZh: '堪萨斯城', cityEn: 'Kansas City', countryZh: '美国', countryEn: 'United States', lat: 39.0453, lng: -94.581 },
  { id: 'penn', nameZh: '宾夕法尼亚大学博物馆', nameEn: 'Penn Museum', cityZh: '费城', cityEn: 'Philadelphia', countryZh: '美国', countryEn: 'United States', lat: 39.9492, lng: -75.1915 },
  { id: 'aam', nameZh: '旧金山亚洲艺术博物馆', nameEn: 'Asian Art Museum of San Francisco', cityZh: '旧金山', cityEn: 'San Francisco', countryZh: '美国', countryEn: 'United States', lat: 37.7802, lng: -122.4162 },
  { id: 'mfa', nameZh: '波士顿美术博物馆', nameEn: 'Museum of Fine Arts, Boston', cityZh: '波士顿', cityEn: 'Boston', countryZh: '美国', countryEn: 'United States', lat: 42.3394, lng: -71.094 },
  { id: 'freer', nameZh: '美国国立亚洲艺术博物馆', nameEn: 'National Museum of Asian Art', cityZh: '华盛顿', cityEn: 'Washington, D.C.', countryZh: '美国', countryEn: 'United States', lat: 38.8881, lng: -77.026 },
  { id: 'tnm', nameZh: '东京国立博物馆', nameEn: 'Tokyo National Museum', cityZh: '东京', cityEn: 'Tokyo', countryZh: '日本', countryEn: 'Japan', lat: 35.7188, lng: 139.7765 },
  { id: 'guimet', nameZh: '吉美国立亚洲艺术博物馆', nameEn: 'Musée Guimet', cityZh: '巴黎', cityEn: 'Paris', countryZh: '法国', countryEn: 'France', lat: 48.8654, lng: 2.2936 },
  { id: 'rom', nameZh: '皇家安大略博物馆', nameEn: 'Royal Ontario Museum', cityZh: '多伦多', cityEn: 'Toronto', countryZh: '加拿大', countryEn: 'Canada', lat: 43.6677, lng: -79.3948 },
  { id: 'aic', nameZh: '芝加哥艺术博物馆', nameEn: 'Art Institute of Chicago', cityZh: '芝加哥', cityEn: 'Chicago', countryZh: '美国', countryEn: 'United States', lat: 41.8796, lng: -87.6237 },
  { id: 'cma', nameZh: '克利夫兰艺术博物馆', nameEn: 'Cleveland Museum of Art', cityZh: '克利夫兰', cityEn: 'Cleveland', countryZh: '美国', countryEn: 'United States', lat: 41.5089, lng: -81.6116 },
]

export const relics = [
  {
    id: 'yixian-bm', museumId: 'bm', category: 'sculpture', image: asset('bm-luohan.jpg'),
    nameZh: '易县三彩罗汉坐像', nameEn: 'Yixian glazed Luohan', dateZh: '辽代，907–1125', dateEn: 'Liao dynasty, 907–1125',
    mediumZh: '铅釉炻器，高 103 厘米', mediumEn: 'Lead-glazed stoneware, 103 cm high',
    originZh: '河北易县西部山洞', originEn: 'Caves west of Yixian, Hebei', originLat: 39.35, originLng: 115.5,
    descZh: '这尊真人大小的罗汉出自一组十六或十八尊造像。写实面容与沉静神情，使宗教造像呈现近乎肖像般的力量。',
    descEn: 'One of a celebrated group of sixteen or eighteen life-size arhats. Its individualized face gives Buddhist sculpture an arresting, portrait-like presence.',
    accession: '1913,1221.1', source: 'https://www.britishmuseum.org/collection/object/A_1913-1221-1',
    creditZh: '图：Wikimedia Commons；藏品信息：大英博物馆（馆方图片另为 CC BY-NC-SA 4.0）', creditEn: 'Image: Wikimedia Commons; object data: The British Museum (museum image separately offered under CC BY-NC-SA 4.0).',
  },
  {
    id: 'admonitions', museumId: 'bm', category: 'painting', image: asset('bm-admonitions.jpg'),
    nameZh: '《女史箴图》卷', nameEn: 'The Admonitions Scroll', dateZh: '约 5–7 世纪摹本', dateEn: 'Copy, about 5th–7th century',
    mediumZh: '绢本设色手卷，现存九段', mediumEn: 'Ink and colour on silk, nine surviving scenes',
    originZh: '中国，具体作地不详', originEn: 'China; precise place of production unknown', originLat: 35.86, originLng: 104.2,
    descZh: '现存最早的中国叙事画长卷之一，传统上据顾恺之原作而来，以图像阐释张华《女史箴》。',
    descEn: 'Among the earliest surviving Chinese narrative handscrolls, this copy follows a composition traditionally associated with Gu Kaizhi and illustrates Zhang Hua’s Admonitions.',
    accession: '1903,0408,0.1', source: 'https://www.britishmuseum.org/collection/object/A_1903-0408-0-1',
    creditZh: '图：Wikimedia Commons，公有领域；藏品信息：大英博物馆', creditEn: 'Image: Wikimedia Commons, public domain; object data: The British Museum.',
  },
  {
    id: 'david-vases', museumId: 'bm', category: 'ceramic', image: asset('bm-david-vases.jpg'),
    nameZh: '大维德花瓶（一对）', nameEn: 'The David Vases', dateZh: '元代，1351 年', dateEn: 'Yuan dynasty, dated 1351',
    mediumZh: '景德镇青花瓷', mediumEn: 'Underglaze-blue porcelain from Jingdezhen',
    originZh: '江西景德镇', originEn: 'Jingdezhen, Jiangxi', originLat: 29.27, originLng: 117.18,
    descZh: '瓶颈长铭文把这对祭坛瓶精确系年到 1351 年；它们是研究元代青花成熟面貌的关键标尺。',
    descEn: 'Long dedicatory inscriptions date the altar vases precisely to 1351, making them a landmark for the study of mature Yuan blue-and-white porcelain.',
    accession: 'PDF,B.613–614', source: 'https://www.britishmuseum.org/collection/object/A_PDF-B-614',
    creditZh: '图：Wikimedia Commons，公有领域；藏品信息：大英博物馆', creditEn: 'Image: Wikimedia Commons, public domain; object data: The British Museum.',
  },
  {
    id: 'emperor-procession', museumId: 'met', category: 'sculpture', image: asset('met-emperor.jpg'),
    nameZh: '孝文帝礼佛图', nameEn: 'Emperor Xiaowen and his entourage worshipping the Buddha', dateZh: '北魏，约 522–523 年', dateEn: 'Northern Wei dynasty, ca. 522–523',
    mediumZh: '石灰岩，残留彩绘', mediumEn: 'Limestone with traces of pigment',
    originZh: '河南洛阳龙门石窟宾阳中洞', originEn: 'Central Binyang Cave, Longmen, Luoyang, Henan', originLat: 34.556, originLng: 112.478,
    descZh: '皇帝与侍从持花、香炉与供物礼佛。它原与今藏纳尔逊—阿特金斯的皇后礼佛图相对，共同构成宾阳中洞的帝室供养叙事。',
    descEn: 'The emperor and attendants advance with flowers and offerings. It once faced the companion empress procession now in Kansas City inside Longmen’s Central Binyang Cave.',
    accession: '35.146', source: 'https://www.metmuseum.org/art/collection/search/42707',
    creditZh: '图：大都会艺术博物馆，公有领域', creditEn: 'Image: The Metropolitan Museum of Art, public domain.', pairId: 'empress-procession',
  },
  {
    id: 'medicine-buddha', museumId: 'met', category: 'painting', image: asset('met-medicine-buddha.jpg'),
    nameZh: '广胜下寺《药师佛法会图》壁画', nameEn: 'Buddha of Medicine Bhaishajyaguru mural', dateZh: '元代，约 1319 年', dateEn: 'Yuan dynasty, ca. 1319',
    mediumZh: '水性颜料、泥草地仗，高约 7.5 米', mediumEn: 'Water-based pigment over clay-and-straw ground, about 7.5 m high',
    originZh: '山西洪洞广胜下寺', originEn: 'Guangsheng Lower Monastery, Hongdong, Shanxi', originLat: 36.27, originLng: 111.68,
    descZh: '药师佛居中，日光、月光菩萨与十二神将环列。馆方据寺院在地震后于 1303–1319 年间重建，将壁画断代在 14 世纪初。',
    descEn: 'The Medicine Buddha presides over sun and moon bodhisattvas and twelve guardian generals. The Met dates the mural around the monastery’s post-earthquake rebuilding of 1303–1319.',
    accession: '65.29.2', source: 'https://www.metmuseum.org/art/collection/search/42716',
    creditZh: '图：大都会艺术博物馆，公有领域', creditEn: 'Image: The Metropolitan Museum of Art, public domain.',
  },
  {
    id: 'yixian-met', museumId: 'met', category: 'sculpture', image: asset('met-luohan.jpg'),
    nameZh: '易县三彩罗汉坐像', nameEn: 'Arhat (Luohan)', dateZh: '约 1000 年', dateEn: 'ca. 1000',
    mediumZh: '三彩釉炻器，像高 127 厘米', mediumEn: 'Stoneware with three-colour glaze, figure 127 cm high',
    originZh: '河北易县西部山洞', originEn: 'Caves west of Yixian, Hebei', originLat: 39.35, originLng: 115.5,
    descZh: '同属易县罗汉群的一尊，三彩釉在衣褶间流动，写实塑造使每位罗汉保有鲜明个性。',
    descEn: 'A member of the Yixian arhat group, combining flowing sancai glazes with highly individualized modelling.',
    accession: '20.114', source: 'https://www.metmuseum.org/art/collection/search/42722',
    creditZh: '图：大都会艺术博物馆，公有领域', creditEn: 'Image: The Metropolitan Museum of Art, public domain.',
  },
  {
    id: 'water-moon-met', museumId: 'met', category: 'sculpture', image: asset('met-water-moon.jpg'),
    nameZh: '水月观音像', nameEn: 'Avalokiteshvara in Water Moon Form', dateZh: '明代，1385 年', dateEn: 'Ming dynasty, dated 1385',
    mediumZh: '柳木、石膏底，残留彩绘', mediumEn: 'Willow wood with gesso and traces of pigment',
    originZh: '中国北方，具体寺院未定', originEn: 'Northern China; original temple not identified', originLat: 37.2, originLng: 112.5,
    descZh: '观音以“自在坐”倚岩而坐，姿态松弛又具内在张力；背部纪年铭文将其定在 1385 年。',
    descEn: 'Avalokiteshvara sits in “royal ease” against an imagined rock. A dated inscription places the sculpture in 1385.',
    accession: '53.92', source: 'https://www.metmuseum.org/art/collection/search/42727',
    creditZh: '图：大都会艺术博物馆，公有领域', creditEn: 'Image: The Metropolitan Museum of Art, public domain.',
  },
  {
    id: 'nelson-guanyin', museumId: 'nelson', category: 'sculpture', image: asset('nelson-guanyin.jpg'),
    nameZh: '南海观音（水月观音）', nameEn: 'Guanyin of the Southern Sea', dateZh: '辽或金代', dateEn: 'Liao or Jin dynasty',
    mediumZh: '木雕，多层彩绘，高 241.3 厘米', mediumEn: 'Wood with multiple layers of paint, 241.3 cm high',
    originZh: '中国北方，具体寺院未定', originEn: 'Northern China; original temple not identified', originLat: 37.5, originLng: 112.5,
    descZh: '巨大的木雕观音以一腿垂落的自在姿坐于岩座，慈悲形象被赋予从容而亲近人的身体感。',
    descEn: 'This monumental wooden Guanyin rests in a relaxed royal-ease pose on a craggy base, bringing a humane physical presence to the deity of compassion.',
    accession: '34-10', source: 'https://art.nelson-atkins.org/objects/597/guanyin-of-the-southern-sea',
    creditZh: '摄影：本站作者（馆内实拍）；藏品资料：纳尔逊—阿特金斯艺术博物馆', creditEn: 'Photo: project creator (own museum photograph); object data: The Nelson-Atkins Museum of Art.',
  },
  {
    id: 'empress-procession', museumId: 'nelson', category: 'sculpture', image: asset('nelson-empress.jpg'),
    nameZh: '皇后礼佛图', nameEn: 'Offering Procession of the Empress as Donor with Her Court', dateZh: '北魏，约 522 年', dateEn: 'Northern Wei dynasty, ca. 522',
    mediumZh: '深灰石灰岩，残留彩绘', mediumEn: 'Fine dark-gray limestone with traces of colour',
    originZh: '河南洛阳龙门石窟宾阳中洞', originEn: 'Central Binyang Cave, Longmen, Luoyang, Henan', originLat: 34.556, originLng: 112.478,
    descZh: '皇后与宫廷女眷列队礼佛。浮雕在 1930 年代碎裂流散，博物馆依据老照片与拓片将购得残块重新拼合，缺失处以石膏补配。',
    descEn: 'The empress and her court proceed in worship. After the relief was fragmented in the 1930s, acquired pieces were reassembled using historic photographs and rubbings, with losses filled in plaster.',
    accession: '40-38', source: 'https://art.nelson-atkins.org/objects/8976/offering-procession-of-the-empress-as-donor-with-her-court',
    creditZh: '图：Daderot / Wikimedia Commons；藏品信息：纳尔逊—阿特金斯艺术博物馆', creditEn: 'Image: Daderot / Wikimedia Commons; object data: The Nelson-Atkins Museum of Art.', pairId: 'emperor-procession',
  },
  {
    id: 'saluzi', museumId: 'penn', category: 'sculpture', image: asset('penn-saluzi.jpg'),
    nameZh: '昭陵六骏·飒露紫', nameEn: 'Saluzi, one of the Six Steeds of Zhaoling', dateZh: '唐代，649 年', dateEn: 'Tang dynasty, 649',
    mediumZh: '石灰岩浅浮雕', mediumEn: 'Carved limestone bas-relief',
    originZh: '陕西礼泉九嵕山昭陵', originEn: 'Zhaoling, Mount Jiuzong, Liquan, Shaanxi', originLat: 34.68, originLng: 108.21,
    descZh: '飒露紫在 621 年洛阳之战中中箭，浮雕刻画丘行恭为战马拔箭，是六骏中唯一出现人物的一幅。',
    descEn: 'Saluzi was struck by an arrow in the 621 siege of Luoyang. General Qiu Xinggong removes it—the only one of the six reliefs to include a human figure.',
    accession: 'C395', source: 'https://collections.penn.museum/collections/object/167942',
    creditZh: '摄影：本站作者（馆内实拍）；藏品资料：宾夕法尼亚大学博物馆', creditEn: 'Photo: project creator (own museum photograph); object data: Penn Museum.',
  },
  {
    id: 'quanmaogua', museumId: 'penn', category: 'sculpture', image: asset('penn-quanmaogua.jpg'),
    nameZh: '昭陵六骏·拳毛騧', nameEn: 'Quanmaogua, one of the Six Steeds of Zhaoling', dateZh: '唐代，649 年', dateEn: 'Tang dynasty, 649',
    mediumZh: '石灰岩浅浮雕', mediumEn: 'Carved limestone bas-relief',
    originZh: '陕西礼泉九嵕山昭陵', originEn: 'Zhaoling, Mount Jiuzong, Liquan, Shaanxi', originLat: 34.68, originLng: 108.21,
    descZh: '拳毛騧在 622 年对刘黑闼作战时身中九箭，仍被刻作疾步向前。六骏中两件现藏费城，另四件在西安碑林博物馆。',
    descEn: 'Quanmaogua sustained nine arrow wounds in the 622 campaign against Liu Heita yet strides forward. Two of the six reliefs are in Philadelphia; four remain in Xi’an.',
    accession: 'C396', source: 'https://collections.penn.museum/collections/object/239945',
    creditZh: '摄影：本站作者（馆内实拍）；藏品资料：宾夕法尼亚大学博物馆', creditEn: 'Photo: project creator (own museum photograph); object data: Penn Museum.',
  },
  {
    id: 'bronze-rhino', museumId: 'aam', category: 'bronze', image: asset('aam-rhino.jpg'),
    nameZh: '犀牛形青铜尊', nameEn: 'Ritual vessel in the shape of a rhinoceros', dateZh: '商代晚期，约前 1100–1050 年', dateEn: 'Late Shang dynasty, probably 1100–1050 BCE',
    mediumZh: '青铜，高 22.8 厘米', mediumEn: 'Bronze, 22.8 cm high',
    originZh: '中国，具体铸造地不详', originEn: 'China; precise foundry location unknown', originLat: 35.86, originLng: 104.2,
    descZh: '器腹内铸有 27 字铭文，馆方释为与贝币贮藏有关。写实犀牛外形与礼仪功能在同一件器物上相遇。',
    descEn: 'A 27-graph inscription is cast inside the belly and interpreted by the museum in connection with storing cowrie “money.” Naturalistic animal form meets ritual function.',
    accession: 'B60B1+', source: 'https://searchcollection.asianart.org/objects/5145/ritual-vessel-in-the-shape-of-a-rhinoceros',
    creditZh: '图：Marshall Astor / Wikimedia Commons（CC BY-SA）；藏品信息：旧金山亚洲艺术博物馆', creditEn: 'Image: Marshall Astor / Wikimedia Commons (CC BY-SA); object data: Asian Art Museum.',
  },
  {
    id: 'nine-dragons', museumId: 'mfa', category: 'painting', image: asset('mfa-nine-dragons.jpg'),
    nameZh: '陈容《九龙图》卷', nameEn: 'Nine Dragons', dateZh: '南宋，1244 年', dateEn: 'Southern Song dynasty, dated 1244',
    mediumZh: '纸本水墨设色，画心长 958.4 厘米', mediumEn: 'Ink and colour on paper, image 958.4 cm long',
    originZh: '中国，具体作地不详', originEn: 'China; precise place of production unknown', originLat: 27.75, originLng: 118.0,
    descZh: '陈容以泼墨、留白与飞动线条，让九条龙在云水间时隐时现；长卷本身像一段不断生成的天气。',
    descEn: 'Chen Rong’s splashed ink, voids, and flying lines make nine dragons surface and vanish through cloud and water—the handscroll unfolds like weather in motion.',
    accession: '17.1697', source: 'https://collections.mfa.org/objects/28526',
    creditZh: '图：Wikimedia Commons，公有领域；藏品信息：波士顿美术博物馆', creditEn: 'Image: Wikimedia Commons, public domain; object data: Museum of Fine Arts, Boston.',
  },
  {
    id: 'luo-nymph', museumId: 'freer', category: 'painting', image: asset('freer-luo-nymph.jpg'),
    nameZh: '《洛神赋图》卷', nameEn: 'Nymph of the Luo River', dateZh: '南宋，12 世纪中叶至 13 世纪中叶', dateEn: 'Southern Song, mid-12th to mid-13th century',
    mediumZh: '绢本水墨设色', mediumEn: 'Ink and colour on silk',
    originZh: '中国，具体作地不详', originEn: 'China; precise place of production unknown', originLat: 34.62, originLng: 112.45,
    descZh: '手卷以连续画面讲述曹植与洛神相遇、别离的故事。馆方将其列为传顾恺之原作的三件重要宋代摹本之一。',
    descEn: 'A continuous handscroll narrates Cao Zhi’s meeting and parting with the river goddess. The museum identifies it as one of three important Song copies of a composition traditionally attributed to Gu Kaizhi.',
    accession: 'F1914.53', source: 'https://collections.si.edu/search/detail/edanmdm:fsg_F1914.53',
    creditZh: '图：Wikimedia Commons，公有领域；藏品信息：美国国立亚洲艺术博物馆', creditEn: 'Image: Wikimedia Commons, public domain; object data: National Museum of Asian Art.',
  },
  {
    id: 'hibiscus', museumId: 'tnm', category: 'painting', image: asset('tnm-hibiscus.jpg'),
    nameZh: '李迪《红白芙蓉图》', nameEn: 'Red and White Cotton Rosemallow', dateZh: '南宋，1197 年', dateEn: 'Southern Song dynasty, 1197',
    mediumZh: '绢本设色，两幅', mediumEn: 'Colour on silk, pair of hanging scrolls',
    originZh: '南宋宫廷，临安（今杭州，推定）', originEn: 'Southern Song court, Lin’an (modern Hangzhou, inferred)', originLat: 30.274, originLng: 120.155,
    descZh: '白芙蓉晨开，渐转粉红至深红。两幅都有 1197 年李迪款，是少见的 12 世纪有款宫廷花鸟画，现为日本国宝。',
    descEn: 'The flower opens white in the morning and gradually reddens. Both scrolls are signed and dated 1197—rare signed works by the court painter Li Di and a Japanese National Treasure.',
    accession: 'TA-137', source: 'https://www.tnm.jp/modules/r_collection/index.php?colid=TA137&controller=dtl&lang=en',
    creditZh: '图：Google Art Project / Wikimedia Commons；藏品信息：东京国立博物馆', creditEn: 'Image: Google Art Project / Wikimedia Commons; object data: Tokyo National Museum.',
  },
  {
    id: 'pig-dragon', museumId: 'guimet', category: 'jade', image: asset('guimet-pig-dragon.jpg'),
    nameZh: '玉猪龙', nameEn: 'Pig-Dragon (zhulong)', dateZh: '公元前 4 千纪', dateEn: '4th millennium BCE',
    mediumZh: '绿软玉，高 15.3 厘米', mediumEn: 'Green nephrite, 15.3 cm high',
    originZh: '红山文化区域（中国东北，类型学归属）', originEn: 'Hongshan cultural region, northeast China (typological attribution)', originLat: 42.2, originLng: 119.0,
    descZh: '猪首与蜷曲龙身围合成环，被视为中国早期龙形玉器的重要类型。馆方记录其确切出土地未明。',
    descEn: 'A pig-like head joins a coiled, ring-shaped body—an important early jade “dragon” type. The museum does not record a precise findspot.',
    accession: 'MG18396', source: 'https://www.guimet.fr/en/our-collections/china/pig-dragon-zhulong',
    creditZh: '图：RMN-Grand Palais / Musée Guimet / Thierry Ollivier', creditEn: 'Image: RMN-Grand Palais / Musée Guimet / Thierry Ollivier.',
  },
  {
    id: 'polo-player', museumId: 'guimet', category: 'ceramic', image: asset('guimet-polo.jpg'),
    nameZh: '彩绘陶打马球女俑', nameEn: 'Female polo player', dateZh: '唐代，约 750 年', dateEn: 'Tang dynasty, ca. 750',
    mediumZh: '红陶、化妆土与彩绘', mediumEn: 'Red terracotta, slip and paint',
    originZh: '中国，确切墓葬未明', originEn: 'China; exact tomb context unknown', originLat: 34.34, originLng: 108.94,
    descZh: '女骑手身体前倾、策马追球。它既是墓中明器，也保存了盛唐长安社会吸纳中亚马球文化的一个瞬间。',
    descEn: 'The rider leans into the chase. A tomb figure, it also preserves a vivid trace of polo culture entering cosmopolitan Tang Chang’an through exchanges with Central Asia.',
    accession: 'MA 6118', source: 'https://www.guimet.fr/en/our-collections/china/female-polo-player',
    creditZh: '图：MNAAG / RMN-Grand Palais / Roger Asselberghs', creditEn: 'Image: MNAAG / RMN-Grand Palais / Roger Asselberghs.',
  },
  {
    id: 'maitreya-paradise', museumId: 'rom', category: 'painting', image: asset('rom-maitreya.jpg'),
    nameZh: '兴化寺《弥勒净土变》壁画', nameEn: 'The Paradise of Maitreya', dateZh: '元代，1298 年', dateEn: 'Yuan dynasty, 1298',
    mediumZh: '泥壁水墨设色', mediumEn: 'Ink and colour on clay wall',
    originZh: '山西稷山兴化寺', originEn: 'Xinghua Monastery, Jishan, Shanxi', originLat: 35.6, originLng: 111.0,
    descZh: '巨幅壁画由朱好古、张伯元等画工绘制，曾装饰一座现已不存的山西佛寺，是皇家安大略博物馆三幅元代寺观壁画之一。',
    descEn: 'Painted by Zhu Haogu, Zhang Boyuan, and their workshop for a Shanxi monastery that no longer survives, this monumental mural is one of three Yuan temple murals in the ROM.',
    accession: 'Bishop White Gallery', source: 'https://www.rom.on.ca/whats-on/galleries/bishop-white-gallery-chinese-temple-art',
    creditZh: '图：Daderot / Wikimedia Commons；藏品信息：皇家安大略博物馆', creditEn: 'Image: Daderot / Wikimedia Commons; object data: Royal Ontario Museum.',
  },
  {
    id: 'aic-buddha', museumId: 'aic', category: 'sculpture', image: asset('aic-buddha.jpg'),
    nameZh: '唐代石雕佛立像', nameEn: 'Standing Buddha', dateZh: '唐代，约 725–750 年', dateEn: 'Tang dynasty, ca. 725–750',
    mediumZh: '石灰岩，残留彩绘，高 219.7 厘米', mediumEn: 'Limestone with traces of polychromy, 219.7 cm high',
    originZh: '传河北北部藏佛寺（馆方注明尚无考古文献确认）', originEn: 'Reportedly Cangfosi, northern Hebei; unconfirmed by archaeology or texts', originLat: 40.8, originLng: 115.5,
    descZh: '丰满挺拔的体量、流畅衣纹与莲座乐伎体现盛唐佛教造像的宏阔气象；所谓“藏佛寺”出土地仍待证实。',
    descEn: 'Robust volume, flowing robes, and celestial musicians around the lotus base exemplify High Tang Buddhist sculpture. The reported Cangfosi provenance remains unverified.',
    accession: '1930.83', source: 'https://www.artic.edu/artworks/86380/buddha',
    creditZh: '图与数据：芝加哥艺术博物馆，CC0 / 公有领域', creditEn: 'Image and data: Art Institute of Chicago, CC0 / public domain.',
  },
  {
    id: 'muqi-dragon', museumId: 'cma', category: 'painting', image: asset('cleveland-dragon.jpg'),
    nameZh: '牧溪《龙图》', nameEn: 'Dragon', dateZh: '南宋，约 1250–1279 年', dateEn: 'Southern Song dynasty, ca. 1250–1279',
    mediumZh: '绢本水墨立轴', mediumEn: 'Hanging scroll, ink on silk',
    originZh: '中国，具体作地不详', originEn: 'China; precise place of production unknown', originLat: 30.27, originLng: 120.15,
    descZh: '龙首从层叠水雾与浪涛间显现，原与《虎图》成对，可能分置观音像两侧；暗沉绢色让墨气更接近一场风暴。',
    descEn: 'A luminous dragon head emerges through tiered mist and waves. Originally paired with Tiger, the scrolls may have flanked an image of Guanyin in a Chan Buddhist setting.',
    accession: '1958.427.1', source: 'https://www.clevelandart.org/art/1958.427.1',
    creditZh: '图与藏品信息：克利夫兰艺术博物馆，开放获取', creditEn: 'Image and object data: Cleveland Museum of Art, Open Access.',
  },
]

export const categories = [
  { id: 'all', zh: '全部', en: 'All' },
  { id: 'painting', zh: '书画 / 壁画', en: 'Painting' },
  { id: 'sculpture', zh: '造像 / 石刻', en: 'Sculpture' },
  { id: 'ceramic', zh: '陶瓷', en: 'Ceramics' },
  { id: 'bronze', zh: '青铜', en: 'Bronze' },
  { id: 'metal', zh: '金银器', en: 'Metalwork' },
  { id: 'lacquer', zh: '漆器', en: 'Lacquer' },
  { id: 'jade', zh: '玉器', en: 'Jade' },
]

export const museumById = Object.fromEntries(museums.map((museum) => [museum.id, museum]))
